apiVersion: v1
kind: Service
metadata:
  name: {{ include "swiss-army-knife.fullname" . }}
  labels:
    {{- include "swiss-army-knife.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "swiss-army-knife.selectorLabels" . | nindent 4 }}
