{{- if .Values.dnsmasq.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: dnsmasq
data:
  config: |-
{{ .Values.dnsmasq.config | indent 4 }}

#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  annotations:
#    meta.helm.sh/release-name: {{ .Release.Name }}
#    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
#  name: pxelinux-cfg-default
#data:
#  default: |- 
#{{ .Values.dnsmasq.default | indent 4 }}
{{- end}}
