{{- if .Values.haproxy.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: haproxy
data:
  config: |
{{ .Values.haproxy.config | indent 4 }}
{{- end }}
