{{- if .Values.haproxy.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "haproxy"
spec:
  type: ClusterIP
  ports:
  - port: 67
    name: dhcp-udp
    targetPort: 67
    protocol: UDP
  - port: 53
    name: dns-udp
    targetPort: 53
    protocol: UDP
  - port: 53
    name: dhcp-tcp
    targetPort: 53
    protocol: TCP
  - port: 80
    name: http-80
    targetPort: 80
    protocol: TCP
  - port: 443
    name: https-443
    targetPort: 443
    protocol: TCP
  - port: 6443
    name: k8s-api
    targetPort: 6443
    protocol: TCP
  - port: "{{ .Values.nginx.port }}"
    name: http-"{{ .Values.nginx.port }}"
    targetPort: "{{ .Values.nginx.port }}"
    protocol: TCP
  - port: 22623
    name: mco
    targetPort: 22623
    protocol: TCP
  - port: 9000
    name: haproxy
    targetPort: 9000
    protocol: TCP
  selector:
    app: "haproxy"
{{- end }}
