---
apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-post-setup
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.ilm.policy.json \"https://lsdobserve-es-http:9200/_ilm/policy/filebeat-lsdobserve\""
        command:
        - /bin/bash
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.eck-operator.image.repository }}:{{ .Values.eck-operator.image.tag }}
        name: filebeat-ilm-policy
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filbeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.pipeline.json \"https://lsdobserve-es-http:9200/_ingest/pipeline/filebeat-lsdobserve-basic\""
        command:
        - /bin/bash
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.eck-operator.image.repository }}:{{ .Values.eck-operator.image.tag }}
        name: filebeat-pipeline
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filbeat-custom-files
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          name: elastic-filbeat-custom-files
        name: elastic-filbeat-custom-files
---