# Elasticsearch
{{- if .Values.lsdobserve.elastic.enabled -}}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  version: 7.10.0
  auth:
    fileRealm:
    - secretName: lsdobserve-filerealm-01
  nodeSets:
  - name: default
    count: {{ .Values.lsdobserve.elastic.count }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.lsdobserve.elastic.storage }}
        storageClassName: {{ .Values.lsdobserve.elastic.storageClassName }}
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 200m
            limits:
              memory: 4Gi
              cpu: 2
{{- end }}