---
apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-post-setup
spec:
  template:
    spec:
      initContainers:
      - args:
        - /bin/sh
        - -c
        - |
          set -x; while [ $(curl -u elastic:$ELASTIC_PASSWORD -skw '%{http_code}' "https://lsdobserve-es-http:9200" -o /dev/null) -ne 200 ]; do
            sleep 5;
          done
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: wait-for-elastic
      containers:
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.ilm.policy.json \"https://lsdobserve-es-http:9200/_ilm/policy/filebeat-lsdobserve\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-ilm-policy
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filbeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.pipeline.json \"https://lsdobserve-es-http:9200/_ingest/pipeline/filebeat-lsdobserve-basic\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-pipeline
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filbeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.template.json \"https://lsdobserve-es-http:9200/_template/filebeat-7.10.0-lsdobserve\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-template
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filbeat-custom-files
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          name: elastic-filbeat-custom-files
        name: elastic-filbeat-custom-files
---
