# Grafana Route for Openshift
{{- if eq .Values.lsdobserve.clusterType "openshift" -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  host: {{ .Values.lsdobserve.grafana.ingress.url }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: lsdobserve-grafana
    weight: 100
  wildcardPolicy: None
{{- end }}