# Grafana Dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-kubernetes-overview
data:
  grafana-dashboard-kubernetes-overview.json: |-
{{ .Files.Get "dashboards/lsdobserve/grafana-dashboard-kubernetes-overview.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-namespace-details
data:
  grafana-dashboard-namespace-details.json: |-
{{ .Files.Get "dashboards/lsdobserve/grafana-dashboard-namespace-details.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-node-namespace-details
data:
  grafana-dashboard-node-namespace-details.json: |-
{{ .Files.Get "dashboards/lsdobserve/grafana-dashboard-node-namespace-details.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-apiserver
data:
  apiserver.json: |-
{{ .Files.Get "dashboards/kubernetes/apiserver.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-rook-ceph-overview
data:
  rook-ceph-dashboard.json: |-
{{ .Files.Get "dashboards/storage/rook-ceph-dashboard.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-for-prometheus-dashboard
data:
  node-exporter-for-prometheus-dashboard.json: |-
{{ .Files.Get "dashboards/nodes/node-exporter-for-prometheus-dashboard.json" | indent 4}}