
# Grafana Ingress
{{- if or (eq .Values.lsdobserve.clusterType "gke") (eq .Values.lsdobserve.clusterType "rancher") -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: lsdobserve-grafana
spec:
  rules:
  - host: {{ .Values.lsdobserve.grafana.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: lsdobserve-grafana
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
{{- end }}