---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lsdobserve
spec:
  hard:
    requests.cpu: "6"
    limits.cpu: "10"
    requests.memory: "24Gi"
    limits.memory: "32Gi"
    requests.storage: "1Ti"
    persistentvolumeclaims: "20"
    requests.nvidia.com/gpu: 4
    configmaps: "50"
    persistentvolumeclaims: "10"
    pods: "100"
    replicationcontrollers: "50"
    secrets: "100"
    services: "100"
    services.loadbalancers: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lsdobserve
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 80m
      memory: 4Mi
    type: Pod
  - default:
      cpu: 400m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 128Mi
    max:
      cpu: "4"
      memory: 8Gi
    maxLimitRequestRatio:
      cpu: "20"
    min:
      cpu: 10m
      memory: 4Mi
    type: Container

